name: Deploy FastAPI

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Build and Deploy
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/stock-api:latest
          
      - name: Deploy Container
        env:
          IMAGE_NAME: ghcr.io/${{ github.repository_owner }}/stock-api:latest
        run: |
          docker pull $IMAGE_NAME
          docker run -d -p 8000:8000 $IMAGE_NAME
